src/StocksApp.UI/Controllers/StocksController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using StocksApp.Core.DTO;
using StocksApp.Core.ServiceContracts.FinnhubServices;
using StocksApp.Core.ServiceContracts.UserStockServices;
using StocksApp.UI.Models;

namespace StocksApp.UI.Controllers
{
    [Route("[controller]")]
    public class StocksController : Controller
    {
        private readonly TradingOptions _tradingOptions;
        private readonly IConfiguration _configuration;
        private readonly IFinnhubStocksService _finnhubStocksService;
        private readonly IFinnhubCompanyProfileService _finnhubCompanyProfileService;
        private readonly IUserStockGetService _userStockGetService;
        private readonly ILogger<StocksController> _logger;

        /// <summary>
        /// Constructor for StocksController that executes when a new object is created for the class
        /// </summary>
        /// <param name="tradingOptions">Inject TradingOptions config through Options pattern</param>
        /// <param name="finnhubService">Inject FinnhubService</param>
        /// <param name="logger">Inject ILogger object for logging</param>
        public StocksController(IOptions<TradingOptions> tradingOptions, IConfiguration configuration, IFinnhubStocksService finnhubStocksService, IFinnhubCompanyProfileService finnhubCompanyProfileService, IUserStockGetService userStockGetService, ILogger<StocksController> logger)
        {
            _tradingOptions = tradingOptions.Value;
            _configuration = configuration;
            _finnhubStocksService = finnhubStocksService;
            _finnhubCompanyProfileService = finnhubCompanyProfileService;
            _userStockGetService = userStockGetService;
            _logger = logger;
        }

        [Route("/")]
        [Route("[action]/{stock?}")]
        [Route("~/[action]/{stock?}")]
        [AllowAnonymous]
        public async Task<IActionResult> Explore(string? stock, bool showAll = false)
        {
            _logger.LogInformation($"{nameof(Explore)} IAction method of {nameof(StocksController)}");

            List<Dictionary<string, string>>? stocksDictionary = await _finnhubStocksService.GetStocks(); 
            List<Stock> stocks = new List<Stock>();

            if (stocksDictionary is not null)
            {
                // filter stocks
                if (!showAll && _tradingOptions.Top25PopularStocks != null)
                {
                    string[]? Top25PopularStocksList = _tradingOptions.Top25PopularStocks.Split(",");
                    if (Top25PopularStocksList is not null)
                    {
                        stocksDictionary = stocksDictionary.Where(temp => Top25PopularStocksList.Contains(Convert.ToString(temp["symbol"]))).ToList();
                    }
                    ViewBag.showAll = false;
                }
                else {
                    ViewBag.showAll = true;
                }

                // Convert dictionary objects to stock objects
                stocks = stocksDictionary.Select(temp => new Stock() {
                    StockSymbol = Convert.ToString(temp["symbol"]),
                    StockName = Convert.ToString(temp["description"])
                }).ToList();
            }

            // Dictionary<string, object>? selectedStock = await _finnhubService.SearchStocks(stock);
            // ViewBag.Stock = selectedStock;
            ViewBag.Stock = stock;

            return View(stocks);
        }

        [Route("[action]")]
        public async Task<IActionResult> MyStocks()
        {
            Guid userID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            List<UserStockResponse> userStocks = await _userStockGetService.GetUserStocks(userID);

            Dictionary<string, object?> companiesLogo = new Dictionary<string, object?>();
            foreach (UserStockResponse stock in userStocks)
            {
                Dictionary<string, object>? companyDetails = await _finnhubCompanyProfileService.GetCompanyProfile(stock.StockSymbol);
                companiesLogo.Add(stock.StockSymbol, companyDetails["logo"]);
            }
            ViewBag.CompaniesLogo = companiesLogo;
            ViewBag.FinnhubToken = _configuration["FinnhubToken"];

            return View(userStocks);
        }
    }
}

src/StocksApp.UI/Controllers/TradeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Rotativa.AspNetCore;
using StocksApp.Core.DTO;
using StocksApp.Core.ServiceContracts.FinnhubServices;
using StocksApp.Core.ServiceContracts.StocksServices;
using StocksApp.Core.ServiceContracts.UserStockServices;
using StocksApp.UI.Filters.ActionFilters;
using StocksApp.UI.Models;

namespace StocksApp.UI.Controllers
{
    [Route("[controller]")]
    public class TradeController : Controller
    {
        private readonly IFinnhubCompanyProfileService _finnhubCompanyProfileService;
        private readonly IFinnhubStockPriceQuoteService _finnhubStocksPriceQuoteService;
        private readonly TradingOptions _tradingOptions;
        private readonly IConfiguration _configuration;
        private readonly IBuyOrdersService _buyOrdersService;
        private readonly ISellOrdersService _sellOrdersService;
        private readonly IUserStockAddService _userStockAddService;
        private readonly IUserStockDecreaseService _userStockDecreaseService;
        private readonly ILogger<TradeController> _logger;

        /// <summary>
        /// Constructor for TradeController
        /// </summary>
        /// <param name="finnhubService">Inject FinnhubService</param>
        /// <param name="tradingOptions">Inject TradingOptions config through Options pattern</param>
        /// <param name="configuration">Inject IConfiguration</param>
        /// <param name="stocksService">Inject StocksService</param>
        /// <param name="logger">Inject ILogger object for logging</param>
        public TradeController(IFinnhubCompanyProfileService finnhubCompanyProfileService, IFinnhubStockPriceQuoteService finnhubStockPriceQuoteService, IOptions<TradingOptions> tradingOptions, IConfiguration configuration, IBuyOrdersService buyOrdersService, ISellOrdersService sellOrdersService, IUserStockAddService userStockAddService, IUserStockDecreaseService userStockDecreaseService, ILogger<TradeController> logger) 
        {
            _finnhubCompanyProfileService = finnhubCompanyProfileService;
            _finnhubStocksPriceQuoteService = finnhubStockPriceQuoteService;
            _tradingOptions = tradingOptions.Value;
            _configuration = configuration;
            _buyOrdersService = buyOrdersService;
            _sellOrdersService = sellOrdersService;
            _userStockAddService = userStockAddService;
            _userStockDecreaseService = userStockDecreaseService;
            _logger = logger;
        }

        [Route("[action]/{stockSymbol}")]
        [Route("~/[controller]/{stockSymbol}")]
        public async Task<IActionResult> Index(string stockSymbol, bool succeeded = true)
        {
            _logger.LogInformation($"{nameof(Index)} IAction method of {nameof(TradeController)} controller");

            if (string.IsNullOrEmpty(stockSymbol))
            {
                stockSymbol = "MSFT";
            }

            Dictionary<string, object>? companyProf = await _finnhubCompanyProfileService.GetCompanyProfile(stockSymbol);    
            Dictionary<string, object>? stockPrice = await _finnhubStocksPriceQuoteService.GetStockPriceQuote(stockSymbol);

            StockTrade stock = new StockTrade() {
                StockSymbol = stockSymbol,
                StockName = Convert.ToString(companyProf["name"]),
                Price = Convert.ToDouble(stockPrice["c"].ToString())
            };
            ViewBag.FinnhubToken = _configuration["FinnhubToken"];
            if (succeeded == false)
            {
                TempData["Succeeded"] = 0;
                ViewBag.ErrorMessage = TempData["Errors"];
            }
            else
            {
                TempData["Succeeded"] = 1;
            }

            return View(stock);
        }

        [Route("[action]")]
        [HttpPost]
        [TypeFilter(typeof(CreateOrderActionFilter))]
        public async Task<IActionResult> BuyOrder(BuyOrderRequest orderRequest)
        {
            _logger.LogInformation($"{nameof(BuyOrder)} IAction method of {nameof(TradeController)} controller");

            Guid userID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            orderRequest.UserID = userID;

            // invoke service method
            BuyOrderResponse buyOrderResponse = new BuyOrderResponse();
            try
            {
                buyOrderResponse = await _buyOrdersService.CreateBuyOrder(orderRequest);
            }
            catch (ArgumentException ex)
            {
                TempData["Errors"] = ex.Message;
                return RedirectToAction(nameof(Index), new { stockSymbol = orderRequest.StockSymbol, succeeded = false });
            }

            UserStockRequest userStockRequest = new UserStockRequest() {
                UserID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)),
                StockSymbol = orderRequest.StockSymbol,
                StockName = orderRequest.StockName,
                Quantity = orderRequest.Quantity,
                LastPrice = orderRequest.Price
            };
            await _userStockAddService.AddUserStock(userStockRequest);

            TempData["Succeeded"] = 1;

            return RedirectToAction(nameof(Orders));
        }

        [Route("[action]")]
        [HttpPost]
        [TypeFilter(typeof(CreateOrderActionFilter))]
        // [TypeFilter(typeof(HandleExceptionFilter))]
        public async Task<IActionResult> SellOrder(SellOrderRequest orderRequest)
        {
            _logger.LogInformation($"{nameof(SellOrder)} IAction method of {nameof(TradeController)} controller");

            Guid userID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            orderRequest.UserID = userID;

            // Invoke service method
            SellOrderResponse sellOrderResponse = new SellOrderResponse();
            try
            {
                sellOrderResponse = await _sellOrdersService.CreateSellOrder(orderRequest);
            }
            catch (ArgumentException ex)
            {
                TempData["Errors"] = ex.Message;
                return RedirectToAction(nameof(Index), new { stockSymbol = orderRequest.StockSymbol, succeeded = false });
            }
            
            UserStockRequest userStockRequest = new UserStockRequest() {
                UserID = userID,
                StockSymbol = orderRequest.StockSymbol,
                StockName = orderRequest.StockName,
                Quantity = orderRequest.Quantity,
                LastPrice = orderRequest.Price
            };
            await _userStockDecreaseService.DecreaseUserStock(userStockRequest);

            TempData["Succeeded"] = 1;

            return RedirectToAction(nameof(Orders));
        }

        [Route("[action]")]
        public async Task<IActionResult> Orders() 
        {
            _logger.LogInformation($"{nameof(Orders)} IAction method of {nameof(TradeController)} controller");

            Guid userID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            List<BuyOrderResponse> userBuyOrders = await _buyOrdersService.GetUserBuyOrders(userID);
            List<SellOrderResponse> userSellOrders = await _sellOrdersService.GetUserSellOrders(userID);

            Orders orders = new Orders() {
                BuyOrders = userBuyOrders,
                SellOrders = userSellOrders
            };

            ViewBag.TradingOptions = _tradingOptions;
            ViewBag.Succeeded = TempData["Succeeded"];

            return View(orders);
        }

        [Route("[action]")]
        public async Task<IActionResult> OrdersPDF()
        {
            Guid userID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            List<IOrderResponse> orders = new List<IOrderResponse>();
            orders.AddRange(await _buyOrdersService.GetUserBuyOrders(userID));
            orders.AddRange(await _sellOrdersService.GetUserSellOrders(userID));
            orders.OrderByDescending(temp => temp.DateAndTimeOfOrder).ToList();

            ViewBag.TradingOptions = _tradingOptions;

            // return view as PDF
            return new ViewAsPdf("OrdersPDF", orders, ViewData)
            {
                PageMargins = new Rotativa.AspNetCore.Options.Margins() { Top = 20, Right = 20, Bottom = 20, Left = 20 },
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape
            };
        }
    }
}

src/StocksApp.UI/ViewComponents/AccountBalanceViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StocksApp.Core.Domain.Entities;
using StocksApp.Core.DTO;
using StocksApp.Core.ServiceContracts.AccountBalanceServices;

namespace StocksApp.UI.ViewComponents
{
    public class AccountBalanceViewComponent : ViewComponent
    {
        private readonly IAccountBalanceGetService _accountBalanceGetService;

        public AccountBalanceViewComponent(IAccountBalanceGetService accountBalanceGetService)
        {
            _accountBalanceGetService = accountBalanceGetService;
        }

        public async Task<IViewComponentResult> InvokeAsync(Guid userID)
        {
            UserAccountBalanceResponse? accountBalance = await _accountBalanceGetService.GetAccountBalance(userID);

            return View(accountBalance);
        } 
    }
}

src/StocksApp.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <link rel="stylesheet" href="~/StyleSheet.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
    integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <title>@ViewBag.Title</title>
</head>

<body>
  <div class="container">

    <div class="page-content">

      <!-- Success dialog -->
      @await Html.PartialAsync("~/Views/Shared/Partials/_SuccessTransactionModal.cshtml")

      <!-- Failed dialog -->
      @await Html.PartialAsync("~/Views/Shared/Partials/_FailedTransactionModal.cshtml")

      <!-- Reminder dialog -->
      @await Html.PartialAsync("~/Views/Shared/Partials/_ReminderModal.cshtml")

      <div class="margin-bottom">
        <div class="flex" id="top-bar-div">

          <div class="flex-1" id="app-title-div">
            <h1 class="app-title mt-13">
              <i class="fa-solid fa-money-bill-trend-up"></i>
              Stocks
            </h1>
          </div>

          <div class="flex-1 pr" id="search-box-div">

            @* <input type="search" class="search-text" placeholder="Search Stocks" name="SearchText">
            <i class="fa-solid fa-gear"></i> *@

            <div class="navbar account-links">
              <ul>
                @if (User.Identity.IsAuthenticated)
                {
                  <li>
                    <i class="fa-solid fa-user"></i>
                    @User.Identity?.Name
                  </li>
                  <li>
                    @{
                      Guid userID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                    }
                    @await Component.InvokeAsync("AccountBalance", new { userID })
                    <a asp-controller="Account" asp-action="Logout">Log out</a>
                  </li>
                }
                else
                {
                  <li>
                    @* <button class="button button-blue-back ml login-button">Login</button> *@
                    <a asp-controller="Account" asp-action="Register">Register</a>
                    <a asp-controller="Account" asp-action="Login">Login</a>
                  </li>
                }
              </ul>
            </div>

          </div>

        </div>
      </div>

      <div class="navbar mb">
        <ul>
          @if (ViewBag.CurrentUrl == "~/Stocks/Explore")
          {
            <li><a asp-controller="Stocks" asp-action="Explore" class="nav-active">Explore</a></li>
          }
          else
          {
            <li><a asp-controller="Stocks" asp-action="Explore">Explore</a></li>
          }

          @if (ViewBag.CurrentUrl == "~/Trade/Index")
          {
            <li><a href="#" class="nav-active" id="tradeAction">Trade</a></li>
          }
          else
          {
            <li><a href="#" id="tradeAction">Trade</a></li>
          }

          @if (ViewBag.CurrentUrl == "~/Trade/Orders")
          {
            <li><a asp-controller="Trade" asp-action="Orders" class="nav-active">Orders</a></li>
          }
          else
          {
            <li><a asp-controller="Trade" asp-action="Orders">Orders</a></li>
          }

          @if (ViewBag.CurrentUrl == "~/Stocks/MyStocks")
          {
            <li><a asp-controller="Stocks" asp-action="MyStocks" class="nav-active">My Stocks</a></li>
          }
          else
          {
            <li><a asp-controller="Stocks" asp-action="MyStocks">My Stocks</a></li>
          }

          @if (ViewBag.CurrentUrl == "~/AccountBalance/Deposit")
          {
            <li><a asp-controller="AccountBalance" asp-action="Deposit" class="nav-active">Deposit</a></li>
          }
          else
          {
            <li><a asp-controller="AccountBalance" asp-action="Deposit">Deposit</a></li>
          }

          @if (ViewBag.CurrentUrl == "~/AccountBalance/Withdraw")
          {
            <li><a asp-controller="AccountBalance" asp-action="Withdraw" class="nav-active">Withdraw</a></li>
          }
          else
          {
            <li><a asp-controller="AccountBalance" asp-action="Withdraw">Withdraw</a></li>
          }
        </ul>
      </div>

      @RenderBody()

    </div>

  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
    crossorigin="anonymous"></script>

  <script type="text/javascript">
      $(function () {
        // Initialize the popover box
        $('#account-balance-popover').popover({
          container: 'body',
          trigger: 'click',
          placement: 'bottom',
          html: true
        });
      });
  </script>

  @await RenderSectionAsync("Scripts", required: false)
</body>

</html>