src/StocksApp.UI/Models/Stock.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StocksApp.UI.Models
{
    public class Stock
    {
        public string? StockSymbol { get; set; }
        public string? StockName { get; set; }

        public override bool Equals(object obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            
            // TODO: write your implementation of Equals() here
            Stock other = (Stock)obj;

            return StockSymbol == other.StockSymbol && StockName == other.StockName;
        }
    }
}

src/StocksApp.UI/Controllers/StocksController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using StocksApp.Core.DTO;
using StocksApp.Core.ServiceContracts.FinnhubServices;
using StocksApp.Core.ServiceContracts.UserStockServices;
using StocksApp.UI.Models;

namespace StocksApp.UI.Controllers
{
    [Route("[controller]")]
    public class StocksController : Controller
    {
        private readonly TradingOptions _tradingOptions;
        private readonly IConfiguration _configuration;
        private readonly IFinnhubStocksService _finnhubStocksService;
        private readonly IFinnhubCompanyProfileService _finnhubCompanyProfileService;
        private readonly IUserStockGetService _userStockGetService;
        private readonly ILogger<StocksController> _logger;

        /// <summary>
        /// Constructor for StocksController that executes when a new object is created for the class
        /// </summary>
        /// <param name="tradingOptions">Inject TradingOptions config through Options pattern</param>
        /// <param name="finnhubService">Inject FinnhubService</param>
        /// <param name="logger">Inject ILogger object for logging</param>
        public StocksController(IOptions<TradingOptions> tradingOptions, IConfiguration configuration, IFinnhubStocksService finnhubStocksService, IFinnhubCompanyProfileService finnhubCompanyProfileService, IUserStockGetService userStockGetService, ILogger<StocksController> logger)
        {
            _tradingOptions = tradingOptions.Value;
            _configuration = configuration;
            _finnhubStocksService = finnhubStocksService;
            _finnhubCompanyProfileService = finnhubCompanyProfileService;
            _userStockGetService = userStockGetService;
            _logger = logger;
        }

        [Route("/")]
        [Route("[action]/{stock?}")]
        [Route("~/[action]/{stock?}")]
        [AllowAnonymous]
        public async Task<IActionResult> Explore(string? stock, bool showAll = false)
        {
            _logger.LogInformation($"{nameof(Explore)} IAction method of {nameof(StocksController)}");

            List<Dictionary<string, string>>? stocksDictionary = await _finnhubStocksService.GetStocks(); 
            List<Stock> stocks = new List<Stock>();

            if (stocksDictionary is not null)
            {
                // filter stocks
                if (!showAll && _tradingOptions.Top25PopularStocks != null)
                {
                    string[]? Top25PopularStocksList = _tradingOptions.Top25PopularStocks.Split(",");
                    if (Top25PopularStocksList is not null)
                    {
                        stocksDictionary = stocksDictionary.Where(temp => Top25PopularStocksList.Contains(Convert.ToString(temp["symbol"]))).ToList();
                    }
                    ViewBag.showAll = false;
                }
                else {
                    ViewBag.showAll = true;
                }

                // Convert dictionary objects to stock objects
                stocks = stocksDictionary.Select(temp => new Stock() {
                    StockSymbol = Convert.ToString(temp["symbol"]),
                    StockName = Convert.ToString(temp["description"])
                }).ToList();
            }

            // Dictionary<string, object>? selectedStock = await _finnhubService.SearchStocks(stock);
            // ViewBag.Stock = selectedStock;
            ViewBag.Stock = stock;

            return View(stocks);
        }

        [Route("[action]")]
        public async Task<IActionResult> MyStocks()
        {
            Guid userID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            List<UserStockResponse> userStocks = await _userStockGetService.GetUserStocks(userID);

            Dictionary<string, object?> companiesLogo = new Dictionary<string, object?>();
            foreach (UserStockResponse stock in userStocks)
            {
                Dictionary<string, object>? companyDetails = await _finnhubCompanyProfileService.GetCompanyProfile(stock.StockSymbol);
                companiesLogo.Add(stock.StockSymbol, companyDetails["logo"]);
            }
            ViewBag.CompaniesLogo = companiesLogo;
            ViewBag.FinnhubToken = _configuration["FinnhubToken"];

            return View(userStocks);
        }
    }
}

src/StocksApp.UI/Controllers/TradeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Rotativa.AspNetCore;
using StocksApp.Core.DTO;
using StocksApp.Core.ServiceContracts.FinnhubServices;
using StocksApp.Core.ServiceContracts.StocksServices;
using StocksApp.Core.ServiceContracts.UserStockServices;
using StocksApp.UI.Filters.ActionFilters;
using StocksApp.UI.Models;

namespace StocksApp.UI.Controllers
{
    [Route("[controller]")]
    public class TradeController : Controller
    {
        private readonly IFinnhubCompanyProfileService _finnhubCompanyProfileService;
        private readonly IFinnhubStockPriceQuoteService _finnhubStocksPriceQuoteService;
        private readonly TradingOptions _tradingOptions;
        private readonly IConfiguration _configuration;
        private readonly IBuyOrdersService _buyOrdersService;
        private readonly ISellOrdersService _sellOrdersService;
        private readonly IUserStockAddService _userStockAddService;
        private readonly IUserStockDecreaseService _userStockDecreaseService;
        private readonly ILogger<TradeController> _logger;

        /// <summary>
        /// Constructor for TradeController
        /// </summary>
        /// <param name="finnhubService">Inject FinnhubService</param>
        /// <param name="tradingOptions">Inject TradingOptions config through Options pattern</param>
        /// <param name="configuration">Inject IConfiguration</param>
        /// <param name="stocksService">Inject StocksService</param>
        /// <param name="logger">Inject ILogger object for logging</param>
        public TradeController(IFinnhubCompanyProfileService finnhubCompanyProfileService, IFinnhubStockPriceQuoteService finnhubStockPriceQuoteService, IOptions<TradingOptions> tradingOptions, IConfiguration configuration, IBuyOrdersService buyOrdersService, ISellOrdersService sellOrdersService, IUserStockAddService userStockAddService, IUserStockDecreaseService userStockDecreaseService, ILogger<TradeController> logger) 
        {
            _finnhubCompanyProfileService = finnhubCompanyProfileService;
            _finnhubStocksPriceQuoteService = finnhubStockPriceQuoteService;
            _tradingOptions = tradingOptions.Value;
            _configuration = configuration;
            _buyOrdersService = buyOrdersService;
            _sellOrdersService = sellOrdersService;
            _userStockAddService = userStockAddService;
            _userStockDecreaseService = userStockDecreaseService;
            _logger = logger;
        }

        [Route("[action]/{stockSymbol}")]
        [Route("~/[controller]/{stockSymbol}")]
        public async Task<IActionResult> Index(string stockSymbol, bool succeeded = true)
        {
            _logger.LogInformation($"{nameof(Index)} IAction method of {nameof(TradeController)} controller");

            if (string.IsNullOrEmpty(stockSymbol))
            {
                stockSymbol = "MSFT";
            }

            Dictionary<string, object>? companyProf = await _finnhubCompanyProfileService.GetCompanyProfile(stockSymbol);    
            Dictionary<string, object>? stockPrice = await _finnhubStocksPriceQuoteService.GetStockPriceQuote(stockSymbol);

            StockTrade stock = new StockTrade() {
                StockSymbol = stockSymbol,
                StockName = Convert.ToString(companyProf["name"]),
                Price = Convert.ToDouble(stockPrice["c"].ToString())
            };
            ViewBag.FinnhubToken = _configuration["FinnhubToken"];
            if (succeeded == false)
            {
                TempData["Succeeded"] = 0;
                ViewBag.ErrorMessage = TempData["Errors"];
            }
            else
            {
                TempData["Succeeded"] = 1;
            }

            return View(stock);
        }

        [Route("[action]")]
        [HttpPost]
        [TypeFilter(typeof(CreateOrderActionFilter))]
        public async Task<IActionResult> BuyOrder(BuyOrderRequest orderRequest)
        {
            _logger.LogInformation($"{nameof(BuyOrder)} IAction method of {nameof(TradeController)} controller");

            Guid userID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            orderRequest.UserID = userID;

            // invoke service method
            BuyOrderResponse buyOrderResponse = new BuyOrderResponse();
            try
            {
                buyOrderResponse = await _buyOrdersService.CreateBuyOrder(orderRequest);
            }
            catch (ArgumentException ex)
            {
                TempData["Errors"] = ex.Message;
                return RedirectToAction(nameof(Index), new { stockSymbol = orderRequest.StockSymbol, succeeded = false });
            }

            UserStockRequest userStockRequest = new UserStockRequest() {
                UserID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)),
                StockSymbol = orderRequest.StockSymbol,
                StockName = orderRequest.StockName,
                Quantity = orderRequest.Quantity,
                LastPrice = orderRequest.Price
            };
            await _userStockAddService.AddUserStock(userStockRequest);

            TempData["Succeeded"] = 1;

            return RedirectToAction(nameof(Orders));
        }

        [Route("[action]")]
        [HttpPost]
        [TypeFilter(typeof(CreateOrderActionFilter))]
        // [TypeFilter(typeof(HandleExceptionFilter))]
        public async Task<IActionResult> SellOrder(SellOrderRequest orderRequest)
        {
            _logger.LogInformation($"{nameof(SellOrder)} IAction method of {nameof(TradeController)} controller");

            Guid userID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            orderRequest.UserID = userID;

            // Invoke service method
            SellOrderResponse sellOrderResponse = new SellOrderResponse();
            try
            {
                sellOrderResponse = await _sellOrdersService.CreateSellOrder(orderRequest);
            }
            catch (ArgumentException ex)
            {
                TempData["Errors"] = ex.Message;
                return RedirectToAction(nameof(Index), new { stockSymbol = orderRequest.StockSymbol, succeeded = false });
            }
            
            UserStockRequest userStockRequest = new UserStockRequest() {
                UserID = userID,
                StockSymbol = orderRequest.StockSymbol,
                StockName = orderRequest.StockName,
                Quantity = orderRequest.Quantity,
                LastPrice = orderRequest.Price
            };
            await _userStockDecreaseService.DecreaseUserStock(userStockRequest);

            TempData["Succeeded"] = 1;

            return RedirectToAction(nameof(Orders));
        }

        [Route("[action]")]
        public async Task<IActionResult> Orders() 
        {
            _logger.LogInformation($"{nameof(Orders)} IAction method of {nameof(TradeController)} controller");

            Guid userID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            List<BuyOrderResponse> userBuyOrders = await _buyOrdersService.GetUserBuyOrders(userID);
            List<SellOrderResponse> userSellOrders = await _sellOrdersService.GetUserSellOrders(userID);

            Orders orders = new Orders() {
                BuyOrders = userBuyOrders,
                SellOrders = userSellOrders
            };

            ViewBag.TradingOptions = _tradingOptions;
            ViewBag.Succeeded = TempData["Succeeded"];

            return View(orders);
        }

        [Route("[action]")]
        public async Task<IActionResult> OrdersPDF()
        {
            Guid userID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            List<IOrderResponse> orders = new List<IOrderResponse>();
            orders.AddRange(await _buyOrdersService.GetUserBuyOrders(userID));
            orders.AddRange(await _sellOrdersService.GetUserSellOrders(userID));
            orders.OrderByDescending(temp => temp.DateAndTimeOfOrder).ToList();

            ViewBag.TradingOptions = _tradingOptions;

            // return view as PDF
            return new ViewAsPdf("OrdersPDF", orders, ViewData)
            {
                PageMargins = new Rotativa.AspNetCore.Options.Margins() { Top = 20, Right = 20, Bottom = 20, Left = 20 },
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape
            };
        }
    }
}

src/StocksApp.UI/ViewComponents/SelectedStockViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using StocksApp.Core.ServiceContracts.FinnhubServices;

namespace StocksApp.UI.ViewComponents
{
    public class SelectedStockViewComponent : ViewComponent
    {
        private readonly TradingOptions _tradingOptions;
        private readonly IFinnhubCompanyProfileService _finnhubCompanyProfileService;
        private readonly IFinnhubStockPriceQuoteService _finnhubStocksPriceQuoteService;
        private readonly IConfiguration _configuration;

        public SelectedStockViewComponent(IOptions<TradingOptions> tradingOptions, IFinnhubCompanyProfileService finnhubCompanyProfileService, IFinnhubStockPriceQuoteService finnhubStocksPriceQuoteService, IConfiguration configuration)
        {
            _tradingOptions = tradingOptions.Value;
            _finnhubCompanyProfileService = finnhubCompanyProfileService;
            _finnhubStocksPriceQuoteService = finnhubStocksPriceQuoteService;
            _configuration = configuration;
        }

        public async Task<IViewComponentResult> InvokeAsync(string? stockSymbol)
        {
            Dictionary<string, object>? companyProfileDict = null;

            if (stockSymbol != null)
            {
                companyProfileDict = await _finnhubCompanyProfileService.GetCompanyProfile(stockSymbol);
                var stockProfileDict = await _finnhubStocksPriceQuoteService.GetStockPriceQuote(stockSymbol);
                if (stockProfileDict != null && companyProfileDict != null) 
                {
                    companyProfileDict.Add("price", stockProfileDict["c"]);
                }
            }

            if (companyProfileDict != null && companyProfileDict.ContainsKey("logo"))
            {
                return View(companyProfileDict);
            }
            else
            {
                return Content("");
            }
        } 
    }
}

src/StocksApp.UI/Views/Stocks/Explore.cshtml
@model IEnumerable<Stock>

@{
  ViewBag.Title = "Explore";
  ViewBag.CurrentUrl = "~/Stocks/Explore";
}

<div class="flex">

  <div class="flex-1">
    <!-- Breadcrums -->
    <div class="text-grey ml">
      <span>Stocks</span>
      <i class="fa-solid fa-caret-right"></i>
      <span>Explore</span>
    </div>
  </div>

  <div class="flex-1 text-right"></div>
</div>

<div class="flex stocks-list">

  <div class="flex-1" id="stocks-list">
    <div class="box">
      <div class="flex">

        <div class="flex-1">
          <h4 class="text-grey">Stocks</h4>
        </div>

        @if (ViewBag.showAll == true)
        {
          <div class="flex-1 text-right">
            <a href="~/Stocks/Explore?showAll=false" class="mr">Show less</a>
          </div>
        }
        else
        {
          <div class="flex-1 text-right">
            <a href="~/Stocks/Explore?showAll=true" class="mr">Show all stocks</a>
          </div>
        }

      </div>

      <!-- stocks list -->
      <ul class="list">
        @foreach (Stock stock in Model)
        {
          <li>
            @if (Context.Request.Query.ContainsKey("showAll"))
            {
              <a href="~/Stocks/Explore/@stock.StockSymbol?showAll=@Context.Request.Query["showAll"]">
                <h4>@stock.StockName</h4>
                <div class="text-grey">(@stock.StockSymbol)</div>
              </a>
            }
            else 
            {
              <a href="~/Stocks/Explore/@stock.StockSymbol">
                <h4>@stock.StockName</h4>
                <div class="text-grey">(@stock.StockSymbol)</div>
              </a>
            }
          </li>
        }
      </ul>

      @if (Model.Count() == 0)
      {
        <div class="mt text-blue">No stocks</div>
      }
    </div>
  </div> 

  <div class="flex-1" id="stock-details">
    @if (ViewBag.Stock != null)
    {
      <vc:selected-stock stock-symbol="@ViewBag.Stock"></vc:selected-stock> 
    } 
  </div>

</div>

@section Scripts {
  <script type="text/javascript">
    function openReminderModal(msg) {
      var myDiv = document.getElementById("reminderModalBody");
      myDiv.innerHTML = msg;
      $('#reminderModal').modal('show');
    }

    $(document).ready(function() {
      document.getElementById("tradeAction").addEventListener("click", function(event) {
        event.preventDefault();
        var stock = "@ViewBag.Stock";
        if (stock == "") {
          var message = "Please choose a stock for trading. ";
          openReminderModal(message);
        }
      });
    });
  </script>
}

src/StocksApp.UI/Views/Stocks/MyStocks.cshtml
@model IEnumerable<UserStockResponse>

@{
  ViewBag.Title = "My stocks";
  ViewBag.CurrentUrl = "~/Stocks/MyStocks";
}

<!-- Breadcrums -->
<div class="flex mb">
  <div class="text-grey ml">
    <span>Stocks</span>
    <i class="fa-solid fa-caret-right"></i>
    <span>My stocks</span>
  </div>

  <div class="flex-1 text-right"></div>
</div>

<form action="" method="get">

  <main class="table">

    <section class="table__header">
      <h2>My Stocks</h2>
    </section>
    @if (Model == null || !Model.Any())
    {
      <span class="m">You have not owned any stocks yet.</span>
    }
    else
    {
      <section class="table__body">
        <table>
          <thead>
            <tr>
              <th></th>
              <th> Stock symbol </th>
              <th> Stock name </th>
              <th> Quantity </th>
              <th> Last price </th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            @foreach (UserStockResponse userStock in @Model)
            {
              <tr>
                <td style="width: 12%;" align="center"> <img src="@ViewBag.CompaniesLogo[userStock.StockSymbol]" width="50px" alt="~/defaultStock.svg"> </td>
                <td style="width: 12%;" class="stockSymbol">@userStock.StockSymbol</td>
                <td style="width: 16%;"> @userStock.StockName </td>
                <td style="width: 13%;"> @userStock.Quantity </td>
                <td style="width: 15%; font-weight: bold;"> <small>$</small><span id="@userStock.StockSymbol">@userStock.LastPrice</span> </td>
                @* <form asp-controller="Trade" asp-action="Index" asp-route-stockSymbol="@userStock.StockSymbol" method="get">
                  <td style="width: 10%;"><button type="submit" class="btn btn-danger"> Trade </button></td>
                </form> *@
                <td style="width: 10%;"><a style="color: #f7f6f6" class="btn btn-primary" href="~/Trade/Index/@userStock.StockSymbol"> Trade </a></td>
              </tr>
            }
          </tbody>
        </table>
      </section>
    }

    <input type="hidden" id="FinnhubToken" value="@ViewBag.FinnhubToken">

  </main>

</form>


@section Scripts {
  <script src="~/Scripts/FinnhubStocksListScript.js"></script>
}